#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ./rep_decrypt_file <encrypted file> <encryption metadata>

from decipher import decrypt_file, parse_args, save_file
import sys

def main():
    encrypted_file, encryption_metadata, decrypted_file_name, out_bytes = parse_args()
    decrypted_file = decrypt_file(encrypted_file, encryption_metadata)
    #send to stdout
    if decrypted_file :
        if out_bytes:
            sys.stdout.buffer.write(decrypted_file)
        else:
            print(str(decrypted_file)[2:-1], end="")
        #se for requerido e a desencriptação tiver sido bem sucedida, salvar o arquivo
        if decrypted_file_name and decrypted_file:
            save_file(decrypted_file, decrypted_file_name)

if __name__ == "__main__":
    main()