#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#rep_subject_credentials <password> <credentials file>

import argparse
import logging
from functions.common_functions import generate_key_pair, save_pub_key


# configurar nível de debug
logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def parse_args() -> tuple:
    # configurar argumentos do comando
    parser = argparse.ArgumentParser()

    parser.add_argument('password', help="Senha para criptografar a chave privada")
    parser.add_argument('credentials_file', help="Arquivo para salvar as credenciais")
    parser.add_argument("-v", '--verbose', help="Aumentar verbosidade", action="store_true")

    args = parser.parse_args()
    if args.verbose:
        logger.setLevel(logging.DEBUG)
        logger.info('Setting log level to DEBUG')
    
    return args.password, args.credentials_file

def main():
    password, credentials_file = parse_args()
    _, pub = generate_key_pair(password)
    logger.debug(f"Chave privada gerada com sucesso")

    save_pub_key(credentials_file, pub)

if __name__ == "__main__":
    main()