#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#./rep_add_subject <session file> <username> <name> <email> <credentials file>

import cryptography
import logging
import os
import requests
import argparse
import json
import sys
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
from encrypt_message import encrypt_message
from functions.common_functions import get_session_data, load_pub_key, verify_repository_signature, is_valid_email
import state_handler as sh
#import commom_functions as cf

logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Função para analisar os argumentos da linha de comando
def parse_args():
    state = sh.load_state()
    state = sh.parse_env(state)

    parser = argparse.ArgumentParser(description="Client to interact with the repository")
    parser.add_argument("session_file", type=str, help="session file")
    parser.add_argument("username", type=str, help="Username")
    parser.add_argument("name", type=str, help="Name")
    parser.add_argument("email", type=str, help="Email")
    parser.add_argument("credentials_file", type=str, help="Credentials file")
    parser.add_argument("-k", '--key', nargs=1, help="Path to the key file")
    parser.add_argument("-r", '--repo', nargs=1, help="Address:Port of the repository")
    parser.add_argument("-v", '--verbose', help="Increase verbosity", action="store_true")

    args = parser.parse_args()
    sh.increase_verbose(args.verbose)
    state = sh.get_param_state(args.key, args.repo, state)

    # Verifica se o arquivo de chave pública existe
    if not os.path.exists(args.credentials_file):
        logger.error(f'Credentials file not found: {args.credentials_file}')
        sys.exit(-1)

    # Verifica se o e-mail é válido
    if not is_valid_email(args.email):
        logger.error(f"Invalid email format: {args.email}")
        sys.exit(-1)
   

    sh.save(state)
        
    return state, args.session_file, args.username, args.name, args.email, args.credentials_file

def add_subject(repo_address,session_file, username, name, email,credentials_file,repo_key):

    session_id, session_key = get_session_data(session_file) #ok
    
    #carregar chave publica da pessoa que quer adicionar
    public_key = load_pub_key(credentials_file) 
    
    pem = public_key.public_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PublicFormat.SubjectPublicKeyInfo).decode('utf-8')
    
    data = {
        "username": username,
        "name": name,
        "email": email,
        "public_key": pem
    }

    payload= encrypt_message(data,session_key)

    try:
        url = f"http://{repo_address}/subject/add"
        data_to_send = {
            "encrypted_data": payload,
            "session_id": session_id
        }

        # Envia a solicitação POST para o servidor
        response = requests.post(url, json=data_to_send)
        response.raise_for_status()  # Raises an error if the response is an HTTP error code
        try:
            server_response = response.json()  # Tenta interpretar o conteúdo como JSON
        except ValueError:
            server_response = response.text  # Se não for JSON, trata como texto
        
        repo_key = serialization.load_pem_public_key(repo_key.encode())
        data= json.dumps(data).encode('utf-8')
        if verify_repository_signature(data, bytes.fromhex(server_response["signature"]), repo_key):
            print("Subject added successfully!")
            return 0
        else:
            print("Signature not valid...")
            return -1
        
    except Exception as e:
        raise ValueError(f"Error to add: {e}")
    

def main():
    state, session_file,username, name, email, credentials_file = parse_args()

    repo_key = state["REP_PUB_KEY"]
    repo_address = state["REP_ADDRESS"]

    logger.debug("state: %s", state)
    logger.debug("state: %s", state)
   
    add_subject(repo_address,session_file, username, name, email,credentials_file,repo_key)


if __name__ == "__main__":
    main()