#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#rep_add_doc <session file> <document name> <file>


import logging
import sys
import json
import os
import requests
import argparse
import state_handler as sh
from functions.cipher import encrypt_file
from functions.common_functions import get_session_data
from functions.encrypt_message import encrypt_message

#set debug level
logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def parse_args():
    #parse_env e parse_args ajustam o estado usando variáveis de ambiente e argumentos.
    state = sh.load_state()
    state = sh.parse_env(state)

    parser = argparse.ArgumentParser(prog='rep_add_doc', usage='%(prog)s <session_file> <document_name> <file>')
    parser.add_argument("session_file", help="Your session file")
    parser.add_argument("document_name", help="Name of the document to be added")
    parser.add_argument("file", help="File handler to upload")
    parser.add_argument("-k", '--key', nargs=1, help="Path to the key file")
    parser.add_argument("-r", '--repo', nargs=1, help="Address:Port of the repository")
    parser.add_argument("-v", '--verbose', help="Increase verbosity", action="store_true")

    args = parser.parse_args()
    sh.increase_verbose(args.verbose)

    state = sh.get_param_state(args.key, args.repo, state)

    sh.save(state)
    
    return state, args.file, args.document_name, args.session_file


def main():
    state, local_file, document_name, session_file = parse_args()

    logger.debug("state: %s", state)

    url = f"http://{state['REP_ADDRESS']}/add_document"


    #encrypt file
    key = os.urandom(16)  # Generate 16 random bytes for AES-128
    iv = os.urandom(16)   # Generate 16 random bytes for IV

    metadata, file_digest, ciphertext = encrypt_file(local_file, key, iv)

    with open('files/'+file_digest, 'wb') as file:
        file.write(ciphertext)

    files = {'file': open('files/'+file_digest, 'rb')}

    data_to_send = json.dumps({
        'document_name': document_name,
        'file_digest': file_digest,
        'metadata': json.dumps(metadata)
    })

    session_id, session_key = get_session_data(session_file)

    encrypted_message = encrypt_message(data_to_send, session_key)
    encrypted_message.update({"session_id": session_id})

    response = requests.post(url, files=files, data=encrypted_message)
    print(response.text)

if __name__ == "__main__":
    main()
