#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json
import sqlite3
import time

# ./rep_drop_role <session file> <role>
import cryptography
import logging
import os
import requests
import argparse
import sys
import json
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
from encrypt_message import encrypt_message
from functions.common_functions import get_session_data, verify_repository_signature
#from delivery2.utils import encrypt_data
import state_handler as sh
#import commom_functions as cf

logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Função para analisar os argumentos da linha de comando
def parse_args():
    state = sh.load_state()
    state = sh.parse_env(state)

    parser = argparse.ArgumentParser(description="Client to interact with the repository")
    parser.add_argument("session_file", type=str, help="session file")
    parser.add_argument("role", type=str, help="Role")
    parser.add_argument("-k", '--key', nargs=1, help="Path to the key file")
    parser.add_argument("-r", '--repo', nargs=1, help="Address:Port of the repository")
    parser.add_argument("-v", '--verbose', help="Increase verbosity", action="store_true")

    args = parser.parse_args()
    sh.increase_verbose(args.verbose)
    state = sh.get_param_state(args.key, args.repo, state)

     # Verifica se session file existe
    if not os.path.exists(args.session_file):
        logger.error(f'Session file not found: {args.session_file}')
        sys.exit(-1)
        

    sh.save(state)
        
    return state, args.session_file, args.role


def assume_role(repo_address,session_file, role,repo_key):

    session_id,session_key = get_session_data(session_file)
    
    data = {
        "role": role
    }

    payload= encrypt_message(data,session_key)

    try:
        url = f"http://{repo_address}/drop_role"
        data_to_send = {
            "encrypted_data": payload,
            "session_id": session_id
        }

        # Envia a solicitação POST para o servidor
        response = requests.post(url, json=data_to_send)
        response.raise_for_status()  # Raises an error if the response is an HTTP error code
        try:
            server_response = response.json()  # Tenta interpretar o conteúdo como JSON
        except ValueError:
            server_response = response.text  # Se não for JSON, trata como texto
        
        repo_key = serialization.load_pem_public_key(repo_key.encode())
        data= json.dumps(data).encode('utf-8')
        if verify_repository_signature(data, bytes.fromhex(server_response["signature"]), repo_key):
            print("Role dropped successfully!")
            return 0
        else:
            print("Signature not valid...")
            return -1
        
    except Exception as e:
        logger.error(f"Failed to drop role.")

def main():
    state, session_file, role = parse_args()

    repo_key = state["REP_PUB_KEY"]
    repo_address = state["REP_ADDRESS"]

    logger.debug("state: %s", state)
   
    assume_role(repo_address,session_file, role, repo_key)


if __name__ == "__main__":
    main()