#!/usr/bin/env python
# -*- coding: utf-8 -*-

# ./rep_create_org <organization> <username> <name> <email> <public key file>

import os
import sys
import json
import logging
import argparse
import requests
import functions.state_handler as sh
from functions.encrypt_data import encrypt_data
from functions.common_functions import encrypt_no_session_message, load_pub_key, is_valid_email

logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def parse_args():
    # Configura o analisador de argumentos
    parser = argparse.ArgumentParser()
    parser.add_argument("-k", '--key', nargs=1, help="Path to the key file")
    parser.add_argument("-r", '--repo', nargs=1, help="Address:Port of the repository")
    parser.add_argument("organization", help="Name of the organization")
    parser.add_argument("username", help="Username associated with the organization")
    parser.add_argument("name", help="Full name of the user")
    parser.add_argument("email", help="Email of the user")
    parser.add_argument("public_key_file", help="Path to the public key file")
    parser.add_argument("-v", '--verbose', help="Increase verbosity", action="store_true")

    args = parser.parse_args()
    if args.verbose:
        logger.setLevel(logging.DEBUG)
        logger.info('Setting log level to DEBUG')

     # Cria o estado inicial com os argumentos fornecidos
    state = {
        "organization": args.organization,
        "username": args.username,
        "name": args.name,
        "email": args.email
    }

    if args.key:
        if not os.path.exists(args.key[0]) or not os.path.isfile(args.key[0]):
            logger.error(f'Key file not found or invalid: {args.key[0]}')
            sys.exit(-1)

        with open(args.key[0], 'r') as f:
            state['REP_PUB_KEY'] = f.read()
            logger.info('Overriding REP_PUB_KEY from command line')

    if args.repo:
        state['REP_ADDRESS'] = args.repo[0]
        logger.info('Overriding REP_ADDRESS from command line')
        

    # Verifica se o arquivo de chave pública existe
    if not os.path.exists(args.public_key_file):
        logger.error(f'Public key file not found: {args.public_key_file}')
        sys.exit(-1)

    # Carrega a chave pública do arquivo
    with open (args.public_key_file, 'r') as f:
        state['public_key'] = f.read()

    # Verifica se o e-mail é válido
    if not is_valid_email(args.email):
        logger.error(f"Invalid email format: {args.email}")
        sys.exit(-1)
   

    return state

def send_request_to_server(state, repo_key):
    # Define a URL do servidor
    url = f"http://{state['REP_ADDRESS']}/organization/create"
    data = {
        "organization": state["organization"],
        "username": state["username"],
        "name": state["name"],
        "email": state["email"],
        "public_key": state["public_key"]
    }
    
    data_to_send, symmetric_key = encrypt_no_session_message(data, repo_key)
    
    try:
        # Envia a solicitação POST para o servidor
        response = requests.post(url, json=data_to_send)
        response.raise_for_status()  # Raises an error if the response is an HTTP error code
        response_data = response.json()
        logger.info(response_data.get("message", "Organization created successfully."))
    except requests.exceptions.HTTPError as e:
        try:
            # Capturar apenas a mensagem de erro simplificada
            error_response = e.response.json()
            logger.error(error_response.get("error", "Unknown error"))
        except ValueError:
            logger.error("Failed to create organization. HTTP Error.")
    except Exception as e:
        logger.error("Unexpected error.")

            
def main():
    # Carrega, ajusta e salva o estado
    state = sh.load_state()
    state = sh.parse_env(state)
    state.update(parse_args())

    # Define o endereço padrão se não estiver no estado
    state['REP_ADDRESS'] = state.get('REP_ADDRESS', '127.0.0.1:5000')
    repo_key = state["REP_PUB_KEY"]
    send_request_to_server(state, repo_key)

    if 'REP_ADDRESS' not in state:
        logger.error("Must define Repository Address")
        sys.exit(-1)

    if 'REP_PUB_KEY' not in state:
        logger.error("Must set the Repository Public Key")
        sys.exit(-1)

    sh.save(state)

if __name__ == '__main__':
    main()