#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import sqlite3
import logging
import argparse
import requests
from cryptography.hazmat.primitives import serialization
from functions.encrypt_message import encrypt_message
from functions.common_functions import get_session_data, verify_repository_signature
import state_handler as sh

logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Função de argumentos
def parse_args():
    state = sh.load_state()
    state = sh.parse_env(state)

    parser = argparse.ArgumentParser(description="Client to manage roles in the repository")
    parser.add_argument("session_file", type=str, help="Session file")
    parser.add_argument("role", type=str, help="Role to modify")
    parser.add_argument("value", type=str, help="Username or Permission to be added")
    parser.add_argument("-k", '--key', nargs=1, help="Path to the key file")
    parser.add_argument("-r", '--repo', nargs=1, help="Address:Port of the repository")
    parser.add_argument("-v", '--verbose', help="Increase verbosity", action="store_true")

    args = parser.parse_args()
    sh.increase_verbose(args.verbose)
    state = sh.get_param_state(args.key, args.repo, state)
    sh.save(state)

    return state, args

# Função para adicionar username a um role
def remove_user_to_role(repo_address, session_file, role, username, repo_key):
    session_id, session_key = get_session_data(session_file)
    data = {"role": role, "username": username}
    payload = encrypt_message(data, session_key)

    try:
        url = f"http://{repo_address}/remove_permission_user"
        data_to_send = {"encrypted_data": payload, "session_id": session_id}
        response = requests.post(url, json=data_to_send)
        response.raise_for_status()

        server_response = response.json()
        repo_key = serialization.load_pem_public_key(repo_key.encode())
        data= json.dumps(data).encode('utf-8')
        if verify_repository_signature(data, bytes.fromhex(server_response["signature"]), repo_key):
            print(f"User '{username}' removed successfully from role '{role}'!")
            return 0
        else:
            print("Signature not valid...")
            return -1
    except Exception as e:
        raise ValueError(f"Error adding user to role: {e}")

# Função para adicionar permission a um role
def remove_permission_role(repo_address, session_file, role, permission, repo_key):
    session_id, session_key = get_session_data(session_file)
    data = {"role": role, "permission": permission}
    payload = encrypt_message(data, session_key)

    try:
        url = f"http://{repo_address}/remove_permission_role"
        data_to_send = {"encrypted_data": payload, "session_id": session_id}
        response = requests.post(url, json=data_to_send)
        response.raise_for_status()

        server_response = response.json()
        repo_key = serialization.load_pem_public_key(repo_key.encode())
        data= json.dumps(data).encode('utf-8')
        if verify_repository_signature(data, bytes.fromhex(server_response["signature"]), repo_key):
            print(f"Permission '{permission}' removed successfully from role '{role}'!")
            return 0
        else:
            print("Signature not valid...")
            return -1
    except Exception as e:
        raise ValueError(f"Error adding permission to role: {e}")

# Identificar automaticamente se o argumento é username ou permission
def main():
    state, args = parse_args()

    repo_key = state["REP_PUB_KEY"]
    repo_address = state["REP_ADDRESS"]
    logger.debug("state: %s", state)

    session_file = args.session_file
    role = args.role
    value = args.value

    # Identificar se o valor é "username" ou "permission"
    if value.islower():  # Verifica se é provavelmente um username (caracteres minúsculos)
        remove_user_to_role(repo_address, session_file, role, value, repo_key)
    elif value.isupper():  # Verifica se é provavelmente uma permission (caracteres maiúsculos)
        remove_permission_role(repo_address, session_file, role, value, repo_key)
    else:
        print("Invalid input: The third argument must be either a username (lowercase) or a permission (uppercase).")

if __name__ == "__main__":
    main()
