#!/usr/bin/env python
# -*- coding: utf-8 -*-

# ./rep_list_orgs

import os
import sys
import json
import logging
import requests

logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def load_state():
    # Carrega o estado a partir de um arquivo JSON
    state = {}
    state_dir = os.path.join(os.path.expanduser('~'), '.sio')
    state_file = os.path.join(state_dir, 'state.json')

    logger.debug('State folder: ' + state_dir)
    logger.debug('State file: ' + state_file)
    
    if os.path.exists(state_file):
        logger.debug('Loading state')
        with open(state_file, 'r') as f:
            state = json.loads(f.read())

    if state is None:
        state = {}

    return state

def parse_env(state):
    # Define o endereço do repositório a partir da variável de ambiente
    if 'REP_ADDRESS' in os.environ:
        state['REP_ADDRESS'] = os.getenv('REP_ADDRESS')
        logger.debug('Setting REP_ADDRESS from Environment to: ' + state['REP_ADDRESS'])

    # Carrega a chave pública do repositório a partir da variável de ambiente
    if 'REP_PUB_KEY' in os.environ:
        rep_pub_key = os.getenv('REP_PUB_KEY')
        logger.debug('Loading REP_PUB_KEY from: ' + rep_pub_key)
        if os.path.exists(rep_pub_key):
            with open(rep_pub_key, 'r') as f:
                state['REP_PUB_KEY'] = f.read()
                logger.debug('Loaded REP_PUB_KEY from Environment')
    return state


def rep_list_orgs():
    # Lista as organizações a partir do repositório
    state = load_state()
    url = f"http://{state['REP_ADDRESS']}/organization/list"

    try:
        response = requests.get(url)
        response.raise_for_status()
        organizations = response.json().get("organizations", [])
        if organizations:
            logger.info("Organizations:")
            for org in organizations:
                logger.info(f" - {org}")
        else:
            logger.info("No organizations found")   

    except requests.exceptions.RequestException as e:
        logger.error(f"Failed to list organizations: {e}")
        sys.exit(1)

def main():
    # Função principal que carrega o estado e lista as organizações
    state = load_state()
    state = parse_env(state)
    rep_list_orgs()

if __name__ == '__main__':
    main()