#!/usr/bin/env python
# -*- coding: utf-8 -*-

# ./rep_suspend_subject <session file> <username>


""" TODO: session file -> dar informação sobre a organização a ser associada ao subject"""

import os
import sys
import json
import logging
import argparse
import requests
import state_handler as sh

logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def parse_args():
    # Configura o analisador de argumentos
    parser = argparse.ArgumentParser()
    parser.add_argument("session_file", help="Path to the session file")
    parser.add_argument("username", help="Username associated with the organization")
    parser.add_argument("-v", '--verbose', help="Increase verbosity", action="store_true")

    args = parser.parse_args()
    if args.verbose:
        logger.setLevel(logging.DEBUG)
        logger.info('Setting log level to DEBUG')

    # Verifica se o arquivo de sessão existe
    if not os.path.exists(args.session_file):
        logger.error(f'Session file not found: {args.session_file}')
        sys.exit(-1)


    # Cria o estado inicial com os argumentos fornecidos
    state = {
        "username": args.username
    }   

    with open(args.session_file, 'r') as f:
        session_file_data = json.load(f)
        state.update(session_file_data)


    return state

def send_request_to_server(state):
    # Define a URL do servidor
    url = f"http://{state['REP_ADDRESS']}/subject/suspend"
    

    data = {
        "session_id":state["session_id"],
        "username": state["username"],
    }

    try:
        # Envia a solicitação POST para o servidor
        response = requests.patch(url, json=data)
        response.raise_for_status()  # Raises an error if the response is an HTTP error code
        logger.info(f"Subject suspended successfully: {response.json().get('message')}")
    except requests.exceptions.RequestException as e:
        logger.error(f"Failed to suspend subject: {e}")

def main():
    # Carrega, ajusta e salva o estado
    state = sh.load_state()
    state = sh.parse_env(state)
    state.update(parse_args())

    # Define o endereço padrão se não estiver no estado
    state['REP_ADDRESS'] = state.get('REP_ADDRESS', '127.0.0.1:5000')

    send_request_to_server(state)

    sh.save(state)

if __name__ == '__main__':
    main()