#!/usr/bin/env python3
# -*- coding: utf-8 -*-
 
import logging
import sys
import os
import requests
import argparse
import json
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
import state_handler as sh

# Configura o nível de debug
logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Função para analisar os argumentos da linha de comando
def parse_args():
    state = sh.load_state()
    state = sh.parse_env(state)

    parser = argparse.ArgumentParser(description="Client to interact with the repository")
    parser.add_argument("session_file", type=str, help="Session file")
    parser.add_argument("-k", '--key', nargs=1, help="Path to the key file")
    parser.add_argument("-r", '--repo', nargs=1, help="Address:Port of the repository")
    parser.add_argument("-v", '--verbose', help="Increase verbosity", action="store_true")

    args = parser.parse_args()
    sh.increase_verbose(args.verbose)
    state = sh.get_param_state(args.key, args.repo, state)

    sh.save(state)
    
    return state, args.session_file

def rep_list_docs(repo_address,session_file):

    with open(session_file,"r") as session_file:
        session_data = session_file.read()
        session_data = json.loads(session_data)
    
    session_id = session_data['session_id']

    url = f"http://{repo_address}/documents/list?session_id={session_id}"

    try:
        data_to_send = session_id

        docs = requests.get(url, json=data_to_send)

        if docs.status_code == 200:
            print("Documents in your Organization:")

            docs = docs.json()
            print(docs['documents'])
        else:
            print("No documents found.")
            
    except requests.exceptions.RequestException as e:
        print(f"Error: {e}")
        sys.exit(1)

def main():
    state, session_file = parse_args()

    repo_address = state["REP_ADDRESS"]

    logger.debug("state: %s", state)
   
    rep_list_docs(repo_address,session_file)


if __name__ == "__main__":
    main()