#!/usr/bin/env python
# -*- coding: utf-8 -*-

# ./rep_add_subject <session file> <username> <name> <email> <credentials file>


""" TODO: session file -> dar informação sobre a organização a ser associada ao subject"""

import os
import re
import sys
import json
import logging
import argparse
import requests
import state_handler as sh
from credentials import load_subj_credentials, gen_subj_credentials
from cryptography.hazmat.primitives import serialization

logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def parse_args():
    # Configura o analisador de argumentos
    parser = argparse.ArgumentParser()
    parser.add_argument("session_file", help="Path to the session file")
    parser.add_argument("username", help="Username associated with the organization")
    parser.add_argument("name", help="Full name of the user")
    parser.add_argument("email", help="Email of the user")
    parser.add_argument("credentials_file", help="Path to the credentials")
    parser.add_argument("-v", '--verbose', help="Increase verbosity", action="store_true")

    args = parser.parse_args()
    if args.verbose:
        logger.setLevel(logging.DEBUG)
        logger.info('Setting log level to DEBUG')

    # Verifica se o arquivo de sessão existe
    if not os.path.exists(args.session_file):
        logger.error(f'Session file not found: {args.session_file}')
        sys.exit(-1)

    # Verifica se o arquivo de credenciais existe
    if not os.path.exists(args.credentials_file):
        logger.error(f'Credentials file not found: {args.credentials_file}')
        sys.exit(-1)

    # Cria o estado inicial com os argumentos fornecidos
    state = {
        "session_file": args.session_file,
        "username": args.username,
        "name": args.name,
        "email": args.email
    }   

    with open(args.credentials_file, "rb") as pem_file:
        pem_data = pem_file.read()

        # Extrair a chave públicac
        public_key_start = pem_data.find(b"-----BEGIN RSA PUBLIC KEY-----")
        public_key_end = pem_data.find(b"-----END RSA PUBLIC KEY-----") + len(b"-----END RSA PUBLIC KEY-----")

        if public_key_start != -1 and public_key_end != -1:
            public_key_pem = pem_data[public_key_start:public_key_end]
        else:
            logger.error("Public key not found in credentials file")  

    state["public_key"] = public_key_pem.decode("utf-8")

    with open(args.session_file, 'r') as f:
        data = f.read()
        json_data = json.loads(data)
        state['session_id'] = json_data.get('session_id')
        logger.info('Loaded session_file from file')

    return state

def send_request_to_server(state):
    # Define a URL do servidor
    url = f"http://{state['REP_ADDRESS']}/subject/add"
    data = {
        "session_id": state["session_id"],
        "username": state["username"],
        "name": state["name"],
        "email": state["email"],
        "public_key": state["public_key"]
    }

    try:
        # Envia a solicitação POST para o servidor
        response = requests.post(url, json=data)
        response.raise_for_status()  # Raises an error if the response is an HTTP error code
        logger.info(f"Subject added successfully: {response.json().get('message')}")
    except requests.exceptions.RequestException as e:
        logger.error(f"Failed to add subject: {e}")

def main():
    # Carrega, ajusta e salva o estado
    state = sh.load_state()
    state = sh.parse_env(state)
    state.update(parse_args())

    # Define o endereço padrão se não estiver no estado
    state['REP_ADDRESS'] = state.get('REP_ADDRESS', '127.0.0.1:5000')

    send_request_to_server(state)

    sh.save(state)

if __name__ == '__main__':
    main()