#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ./rep_create_session <organization> <username> <password> <credentials file> <session file>
import cryptography
import logging
from credentials import load_subj_credentials, gen_subj_credentials
import os
import requests
import argparse
import json
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
import state_handler as sh
import commom_functions as cf

# Configura o nível de debug
logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Função para analisar os argumentos da linha de comando
def parse_args():
    state = sh.load_state()
    state = sh.parse_env(state)

    parser = argparse.ArgumentParser(description="Client to interact with the repository")
    parser.add_argument("organization", type=str, help="Organization name")
    parser.add_argument("username", type=str, help="Username")
    parser.add_argument("password", type=str, help="Password")
    parser.add_argument("credentials_file", type=str, help="File containing client's RSA keys")
    parser.add_argument("session_file", type=str, help="File to save session information")
    parser.add_argument("-k", '--key', nargs=1, help="Path to the key file")
    parser.add_argument("-r", '--repo', nargs=1, help="Address:Port of the repository")
    parser.add_argument("-v", '--verbose', help="Increase verbosity", action="store_true")

    args = parser.parse_args()
    sh.increase_verbose(args.verbose)
    state = sh.get_param_state(args.key, args.repo, state)

    sh.save(state)
    
    return state, args.organization, args.username, args.password, args.credentials_file, args.session_file

def save_session_file(session_file, dict):
    # Salva o conteúdo necessário no arquivo de sessão
    with open(session_file, "w") as f:
        json.dump(dict,f)
    

# Função para criar uma sessão
def create_session(repo_address, organization, username, password, credentials_file, session_file, repo_key):

    # Carrega a chave pública do servidor e prepara a comunicação
    server_public_key = repo_key
    public_key = serialization.load_pem_public_key(server_public_key.encode(), backend=default_backend())   
    server_public_key = public_key

    pub_key, _ = load_subj_credentials(password, credentials_file)
    rsa_public_key = pub_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.PKCS1
    )

    symmetric_key = cf.generate_symmetric_key()
    data = json.dumps({"organization": organization, "username": username})
    encrypted_data, tag, nonce = cf.encrypt_data(data, symmetric_key)
    encrypted_symmetric_key = cf.encrypt_symmetric_key(symmetric_key, server_public_key)

    url = f"http://{repo_address}/create_session"
    data_to_send = {
        "encrypted_key": encrypted_symmetric_key.hex(),
        "encrypted_data": encrypted_data.hex(),
        "nonce": nonce.hex(),
        "tag": tag.hex(),
        "rsa_public_key":rsa_public_key.hex()
    }

    response = requests.post(url, json=data_to_send)
    data_server =response.text
    data_server = json.loads(data_server)
    
    if response.status_code == 201:
        session_id = data_server["session_id"] 
        dict = {"session_id": session_id, "symmetric_key" : symmetric_key.hex()}
        print("Session created successfully!")
        save_session_file(session_file, dict)
    else:
        print("Failed to create session:", response.status_code, response.text)

def main():
    state, organization, username, password, credentials_file, session_file = parse_args()

    repo_key = state["REP_PUB_KEY"]
    repo_address = state["REP_ADDRESS"]

    logger.debug("state: %s", state)
   
    create_session(repo_address, organization, username, password, credentials_file, session_file, repo_key)


if __name__ == "__main__":
    main()