#!/usr/bin/env python
# -*- coding: utf-8 -*-

# ./rep_list_subjects <sessiol

import os
import sys
import json
import logging
import argparse
import state_handler as sh
import requests

logging.basicConfig(format='%(levelname)s\t- %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def parse_args():
    # Configura o analisador de argumentos
    parser = argparse.ArgumentParser()
    parser.add_argument("session_file", help="Session file")
    parser.add_argument("-v", '--verbose', help="Increase verbosity", action="store_true")

    args = parser.parse_args()
    if args.verbose:
        logger.setLevel(logging.DEBUG)
        logger.info('Setting log level to DEBUG')

    state = {}

    # Verifica se o arquivo de chave pública existe
    if not os.path.exists(args.session_file):
        logger.error(f'Session file not found: {args.session_file}')
        sys.exit(-1)

    with open(args.session_file, 'r') as f:
        data = f.read()
        json_data = json.loads(data)
        state['session_id'] = json_data.get('session_id')
        logger.info('Loaded session_file from file')

    return state

def send_request_to_server(state):
    # Define a URL do servidor
    url = f"http://{state['REP_ADDRESS']}/subject/list"
    data = {
        "session_id": state["session_id"]
    }

    try:
        # Envia a solicitação POST para o servidor
        response = requests.post(url, json=data)
        response.raise_for_status()  # Raises an error if the response is an HTTP error code
        logger.info(f"List of subjects: {response.json().get('message')}")
    except requests.exceptions.RequestException as e:
        logger.error(f"Failed to add subject: {e}")

def main():
    # Função principal que carrega o estado e lista as organizações
    state = sh.load_state()
    state = sh.parse_env(state)
    state.update(parse_args())

    state['REP_ADDRESS'] = state.get('REP_ADDRESS', 'localhost:5000')

    send_request_to_server(state)

    sh.save(state)

if __name__ == '__main__':
    main()