#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#rep_subject_credentials <password> <credentials file>
from credentials import gen_subj_credentials, parse_args

def main():
    password, credentials_file = parse_args()
    gen_subj_credentials(password, credentials_file)

if __name__ == "__main__":
    main()